import { Service, User } from "@/types";

export const MOCK_PROVIDERS: (User & { rating: number; reviewCount: number; location: string; tags: string[]; minPrice: number })[] = [
    {
        id: "1",
        name: "Studio La Seine",
        email: "contact@laseine.com",
        role: "PROVIDER",
        avatarUrl: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=400&h=400&fit=crop",
        bio: "Studio d'enregistrement mythique à Paris. Équipement haut de gamme et ingénieurs expérimentés.",
        rating: 4.9,
        reviewCount: 128,
        location: "Paris, France",
        tags: ["Studio", "Mixage", "Mastering"],
        minPrice: 350,
    },
    {
        id: "2",
        name: "Alex Mix Engineer",
        email: "alex@mix.com",
        role: "PROVIDER",
        avatarUrl: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=400&h=400&fit=crop",
        bio: "Ingénieur du son spécialisé Hip-Hop et Pop. 10 ans d'expérience, crédits majeurs.",
        rating: 4.8,
        reviewCount: 45,
        location: "Lyon, France",
        tags: ["Mixage", "Mastering", "Remote"],
        minPrice: 150,
    },
    {
        id: "3",
        name: "BeatMaker Pro",
        email: "beats@pro.com",
        role: "PROVIDER",
        avatarUrl: "https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=400&h=400&fit=crop",
        bio: "Création d'instrumentales sur mesure. Trap, Drill, Afrobeat.",
        rating: 4.7,
        reviewCount: 32,
        location: "Marseille, France",
        tags: ["Beatmaking", "Production"],
        minPrice: 80,
    },
    {
        id: "4",
        name: "Vocal Coach Sarah",
        email: "sarah@coach.com",
        role: "PROVIDER",
        avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop",
        bio: "Coaching vocal pour chanteurs et rappeurs. Améliorez votre technique et votre présence.",
        rating: 5.0,
        reviewCount: 15,
        location: "Bordeaux, France",
        tags: ["Coaching", "Vocal"],
        minPrice: 60,
    },
    {
        id: "5",
        name: "Mastering House",
        email: "mastering@house.com",
        role: "PROVIDER",
        avatarUrl: "https://images.unsplash.com/photo-1516280440614-6697288d5d38?w=400&h=400&fit=crop",
        bio: "Studio de mastering analogique. Donnez à vos titres la chaleur et la puissance qu'ils méritent.",
        rating: 4.9,
        reviewCount: 89,
        location: "Lille, France",
        tags: ["Mastering", "Analog"],
        minPrice: 100,
    },
    {
        id: "6",
        name: "Video Clip Maker",
        email: "video@clip.com",
        role: "PROVIDER",
        avatarUrl: "https://images.unsplash.com/photo-1531384441138-2736e62e0919?w=400&h=400&fit=crop",
        bio: "Réalisation de clips vidéo 4K. Scénario, tournage et montage.",
        rating: 4.6,
        reviewCount: 22,
        location: "Paris, France",
        tags: ["Vidéo", "Clip"],
        minPrice: 500,
    },
    {
        id: "7",
        name: "Session Drummer",
        email: "drummer@session.com",
        role: "PROVIDER",
        avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop",
        bio: "Batteur professionnel disponible pour vos sessions studio ou live.",
        rating: 5.0,
        reviewCount: 10,
        location: "Nantes, France",
        tags: ["Musicien", "Batterie"],
        minPrice: 150,
    },
    {
        id: "8",
        name: "Urban Studio B",
        email: "urban@studio.com",
        role: "PROVIDER",
        avatarUrl: "https://images.unsplash.com/photo-1598653222000-6b7b7a552625?w=400&h=400&fit=crop",
        bio: "Studio spécialisé musique urbaine. Cabine spacieuse et lounge.",
        rating: 4.7,
        reviewCount: 56,
        location: "Lyon, France",
        tags: ["Studio", "Rap"],
        minPrice: 200,
    },
];

export const MOCK_SERVICES: Service[] = [
    {
        id: "s1",
        providerId: "1",
        name: "Session Enregistrement (4h)",
        description: "Demi-journée d'enregistrement avec ingénieur. Cabine A.",
        price: 350,
        duration: 240,
        category: "STUDIO",
    },
    {
        id: "s2",
        providerId: "2",
        name: "Mixage Titre Stereo",
        description: "Mixage complet d'un titre jusqu'à 40 pistes.",
        price: 150,
        duration: 0, // Remote
        category: "MIXING",
    },
];
